api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import StudentViewSet

router = routers.DefaultRouter()
router.register(r'students', StudentViewSet)
urlpatterns = [
    path('', include(router.urls)),
]

djangoProject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from userextend.forms import AuthenticationExtendForm

urlpatterns = [
    path('login/', LoginView.as_view(authentication_form=AuthenticationExtendForm), name='login'),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
    path('api/', include('api.urls')),
    ]

student/models.py
from django.db import models
from teacher.models import Teacher


class Student(models.Model):
    gender_option = (('male', 'Male'), ('female', 'Female'), ('other', 'Other'))

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField()
    is_olympic = models.BooleanField(default=False)
    email = models.EmailField(max_length=200)
    description = models.TextField(max_length=400)
    start_date_time = models.DateTimeField()
    end_date = models.DateField()
    gender = models.CharField(choices=gender_option, max_length=6)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

teacher/models.py
from django.db import models


class Teacher(models.Model):
    course_option = (('python', 'Python'), ('javascript', 'JavaScript'),
                     ('java', 'Java'))

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    department = models.CharField(max_length=40)
    course = models.CharField(choices=course_option, max_length=10)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.course}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'CSS/my_style.css' %}">
</head>
<body>

    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
<img src="../static/NicePng_dog-and-cat-png_561211.png" height="1000px" alt="#" class>

</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light text-center">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'apps' %}">DjangoProject</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {#                {% if request.user.is_authenticated and request.user.is_superuser %}#}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'all_cars' %}">Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'apps' %}">Applications</a>
                    </li>
                    {% if perms.student.add_student or perms.student.view_student %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Students
                            </a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if perms.student.add_student %}
                                    <li><a class="dropdown-item" href="{% url 'create_student' %}">Create Student</a>
                                    </li>
                                {% endif %}
                                {% if perms.student.view_student %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_students' %}">Students List</a>
                                    </li>
                                {% else %}
                                    <li><a href="#" class="dropdown-item text-center">List</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                    {% if perms.teacher.add_teacher or perms.teacher.view_teacher %}
                        <li class="nav-item dropdown" >
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Teachers
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                                {% if perms.teacher.add_teacher %}
                                    <li><a class="dropdown-item" href="{% url 'create_teacher' %}">Create Teacher</a>
                                    </li>
                                {% endif %}
                                {% if perms.teacher.view_teacher %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_teachers' %}">Teachers</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                    {% if perms.student.students_per_teacher %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                All Teachers
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for teacher in get_all_teacher %}
                                    <li><a class="dropdown-item"
                                           href="{% url 'all_students_per_teacher' teacher.id %}">{{ teacher.first_name }} {{ teacher.last_name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}"
                   class="btn btn-outline-primary mr-3">Logout, {{ request.user.username }}</a>
            {% else %}
                <div class="d-flex">
                    <a href="{% url 'create_user' %}" class="btn btn-outline-secondary mx-2">Sign Up</a>
                    <a href="{% url 'login' %}" class="btn btn-outline-success mx-2">Login</a>
                </div>
            {% endif %}
            {#            <form class="d-flex">#}
            {#                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
            {#                <button class="btn btn-outline-success" type="submit">Search</button>#}
            {#            </form>#}
        </div>
    </div>
</nav>